### ISSUE TITLE
32 missing?

### ISSUE THREAD

**Issue by Krinkle** [simevidas/webplatformnews-weekly#1]
Found a link to 32 in my RSS reader (Feedly) as https://github.com/simevidas/webplatformnews-weekly/blob/master/issues/2017-12-25.md, but the file doesn't seem to exist?

**Comment by simevidas** [comment]
Thanks for the heads-up. I forgot that my RSS is auto-generated every time I deploy 😅. There is no weekly issue #32 on Dec 25 — I published #31 yesterday, btw — so I removed it from my RSS, but it seems that Feedly still lists it, even after I hit Refresh. I’m not sure if that‘s a bug or if RSS readers tend to keep RSS items around even when they are removed from the source feed.

**Comment by mems** [comment]
Same thing for 34, 35, 36 and 37. It's missing from the repo (but referenced by the [RSS feed](https://webplatform.news/feed.xml))

**Comment by simevidas** [comment]
Thanks again for the heads-up. I was focused on branching out the weekly into a newsletter that I forgot to update the RSS script. It should be fixed now.

https://webplatform.news/feed.xml
